### ISSUE TITLE
Create favicon from logo

### ISSUE THREAD

**Issue by jonparker** [jonparker/green-webhook#25]

**Comment by jadetrue** [comment]
![Image](https://user-images.githubusercontent.com/39219696/199231057-3dd0c5d8-05b9-4e87-9d42-a4d002eb9443.png)
![Image](https://user-images.githubusercontent.com/39219696/199231056-478cef67-3862-45ac-b392-05204cb1d0b8.png)
![Image](https://user-images.githubusercontent.com/39219696/199231059-b0875e5d-0c42-46a7-8c99-759a6616fdfe.png)
![Image](https://user-images.githubusercontent.com/39219696/199231058-a4bc31fb-0f39-4361-ac91-2db8cfedd8ff.png)
![Image](https://user-images.githubusercontent.com/39219696/199231060-5307ea9c-6b99-4ed2-9b98-de8c3eaa7281.png)
