### ISSUE TITLE
Fix  create new webhook button

### ISSUE THREAD

**Issue by jonparker** [jonparker/green-webhook#29]
Clicking on the create new green webhook button doesn't do anything.

![Image](https://user-images.githubusercontent.com/152131/197784459-4011e38a-4e33-4ca0-ae51-83c0ecd51851.png)

![Image](https://user-images.githubusercontent.com/152131/197784551-ff4e402c-80b4-4059-9042-cba8a065e3c0.png)

Possibly there is something wrong in `web/src/Routes.tsx` but I haven't been able to work out what it is.

**Comment by mr-loop-1** [comment]
The affected part is at
https://github.com/jonparker/green-webhook/blob/5a2c627b7dd318853a8b6ad0aed8f7875d2977b9/web/src/components/Navigation/Navigation.tsx#L37-L39
which, in turn, takes these two values from
https://github.com/jonparker/green-webhook/blob/5a2c627b7dd318853a8b6ad0aed8f7875d2977b9/web/src/Routes.tsx#L37
and there is no matching route for `/newWebhook` in routing

**Comment by mr-loop-1** [comment]
I guess this issue will be there in most of 
There can be two approaches
1. we can assign it to correct route like `buttonTo="/webhooks/new"
2. in `Navigation.tsx`, we can dynamically call the `buttonTo` property on the imported `routes` like 
```js
<Link to={routes[`${buttonTo}`]()}>
```

I guess the second approach would be more portable later on, but `layouts/DefaultLayout.tsx` will also have to be modified since it does not pass any props to the Navigation component.

**Comment by jonparker** [comment]
That's interesting because I don't think that code in the Route has changed since it was generated by Redwood.

Also this route is named `newWebhook`.

```js

          <Route path="/webhooks/new" page={WebhookNewWebhookPage} name="newWebhook" />
```

**Comment by mr-loop-1** [comment]
That's beacuse it isn't resolving to name of our route, but path of our route.
In the same file, this behaves correctly
https://github.com/jonparker/green-webhook/blob/5a2c627b7dd318853a8b6ad0aed8f7875d2977b9/web/src/components/Navigation/Navigation.tsx#L31-L33
here `webhooks()` is the name prop of our route.

**Comment by mr-loop-1** [comment]
As I was expecting, same is the case with 
https://github.com/jonparker/green-webhook/blob/5a2c627b7dd318853a8b6ad0aed8f7875d2977b9/web/src/Routes.tsx#L19
https://github.com/jonparker/green-webhook/blob/5a2c627b7dd318853a8b6ad0aed8f7875d2977b9/web/src/Routes.tsx#L26
Also, @jonparker what is supposed to be there in the idle `+` buttons on "home" and "about" page

**Comment by jonparker** [comment]
@mr-loop-1 that plus button wasn't there before so should be removed.
