### ISSUE TITLE
Create project logo

### ISSUE THREAD

**Issue by jonparker** [jonparker/green-webhook#3]
**Jade:**

This was an idea I found for the logo. Any thoughts on this? 

![Image](https://user-images.githubusercontent.com/39219696/197197147-910830e0-0353-4495-ab68-59ae4e5284f8.svg)

**Jon**

It looks great. You should add it to the project if you want.

**Comment by jadetrue** [comment]
![Image](https://user-images.githubusercontent.com/39219696/199232088-b8dffb46-da9c-4a2d-bfaf-31e552ef299f.png)
![Image](https://user-images.githubusercontent.com/39219696/199232086-bfabd5a8-7b88-4c43-b066-450d514b5ae6.png)
![Image](https://user-images.githubusercontent.com/39219696/199232089-48fbc736-59d9-4958-bd60-1b80f161a5f6.png)
![Image](https://user-images.githubusercontent.com/39219696/199232087-2f13b1bb-48c9-41cb-9631-483d5250ab9a.png)
