### ISSUE TITLE
Start styling the UI/UX Frontend

### ISSUE THREAD

**Issue by jonparker** [jonparker/green-webhook#4]
** Jon **
I haven't thought much about styling but it would be nice to have a some green in the colour pallette.

**Comment by jadetrue** [comment]
#8bc53f - yellow green
#050609 - rich black
#774936 - bole

**Comment by jadetrue** [comment]
@jonparker I've put a [PR](https://github.com/jonparker/green-webhook/pull/15) for the foundation styling... let me know your thoughts! Very weird working on something so separately from the rest of the team!!

**Comment by jonparker** [comment]
Thank you, this is awesome. I've merged the PR in.

**Comment by jonparker** [comment]
@jadetrue there's been a few updates to how endpoints are added in the UI.

It would be great to improve the styling on the edit form if you get a chance.

Also we should add more instructions in the form itself on how to create a webhook.

I guess there's lots of ways to make the UX more friendly.
